package springJPA.domain;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bruce.huang' at '2016/6/17 上午 11:55' with Gradle 2.13
 *
 * @author bruce.huang, @date 2016/6/17 上午 11:55
 */
@Entity
public class Product {
	@Id @GeneratedValue
	private Integer productId;
	private String name;
	private Integer price;
	
	public Product() {
		super();
	}
	public Product(String name, int price) {
		super();
		this.name = name;
		this.price = price;
	}
	public Integer getProductId() {
		return productId;
	}
	public void setProductId(Integer productId) {
		this.productId = productId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public Integer getPrice() {
		return price;
	}
	public void setPrice(Integer price) {
		this.price = price;
	}
	@Override
	public String toString() {
		return "Product [productId=" + productId + ", name=" + name + ", price=" + price + "]";
	}
	
}
