import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ResourceBundle;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bruce.huang' at '2016/6/17 上午 11:55' with Gradle 2.13
 *
 * @author bruce.huang, @date 2016/6/17 上午 11:55
 */
public class EazyDAO {
	private final String DROP_PRODUCT = "DROP TABLE PRODUCT ; " ;
	private final String CREATE_PRODUCT = 
			"CREATE TABLE IF NOT EXISTS PRODUCT ( " + 
				 "PRODUCT_ID bigint NOT NULL AUTO_INCREMENT," +
				 "NAME varchar(255) NOT NULL," +
				 "PRICE int NOT NULL" +
        	")"; 
	private final String INSERT_PRODUCT1 = "INSERT INTO PRODUCT(NAME,PRICE)VALUES('PRODUCT~A','166')" ;
	private final String INSERT_PRODUCT2 = "INSERT INTO PRODUCT(NAME,PRICE)VALUES('PRODUCT~B','255')" ;
	
	
	
	
	
	public Connection conn;
	public EazyDAO(){
		System.out.println("init EazyDAO");
		ResourceBundle dbConfigs = ResourceBundle.getBundle("dbConfig");
    	String jdbc_driveClass = dbConfigs.getString("jdbc_driveClass");
    	String jdbc_url = dbConfigs.getString("jdbc_url");
    	String jdbc_username = dbConfigs.getString("jdbc_username");
    	String jdbc_password = dbConfigs.getString("jdbc_password");
		try {
			Class.forName(jdbc_driveClass);
			conn = DriverManager.getConnection(jdbc_url, jdbc_username , jdbc_password );
			
			initProduct();
			initBill();
			initBillDetail();
		} catch (Exception e) {
			e.printStackTrace();
		}	
	}

	private void initBill() {
		// TODO Auto-generated method stub
		
	}
	private void initProduct() throws SQLException {
    	ResultSet res = null ;
    	ResultSet rr  = null ;
    	//init product
    	conn.prepareStatement(DROP_PRODUCT).execute();					//drop
    	conn.prepareStatement(CREATE_PRODUCT).execute();				//create
    	
    	conn.prepareStatement(INSERT_PRODUCT1).execute();				//insert A
    	
    	PreparedStatement st = conn.prepareStatement(INSERT_PRODUCT2);	//insert B
    	st.execute();
    	rr = st.getGeneratedKeys();										//取得當前的key	裡面只有   欄位:SCOPE_IDENTITY() 型態 BIGINT 數值2(新增了兩筆,所以產生到2)
    	rr.next();
    	System.out.println(rr.getString(1));
    	
    	
    	res = conn.prepareStatement("SELECT * FROM PRODUCT").executeQuery();	//get All test data
    	while(res.next()){
    		ResultSetMetaData metaData = res.getMetaData();
    		for(int i=1 ;i<=metaData.getColumnCount() ;i++){
    			System.out.print("欄位:"+metaData.getColumnName(i)+" 型態:"+metaData.getColumnTypeName(i)+" 值 :");
    			System.out.print(metaData.getColumnTypeName(i).contains("INT")? res.getInt(metaData.getColumnName(i)):res.getString(metaData.getColumnName(i)));
    			System.out.println();
    		}
    		System.out.println("==================");
    	}
	}
    private void initBillDetail() {
		
	}
}
